@baseUrl = http://localhost:3000

###
# @name deleteManyExample
# @prompt id1
# @prompt id2
POST {{baseUrl}}/v1/examples/delete-many HTTP/1.1
Accept: application/json
Content-Type: application/json

{
  "ids": ["{{id1}}","{{id2}}"]
}