@baseUrl = http://localhost:3000

###
# @name updateExample
# @prompt id
# @prompt name
# @prompt phone
PATCH {{baseUrl}}/v1/examples/{{id}} HTTP/1.1
Accept: application/json
Content-Type: application/json

{
  "name": "{{name}}",
  "phone": "{{phone}}"
}