@baseUrl = http://localhost:3000

###
# @name updateManyExample
# @prompt name
# @prompt phone
POST {{baseUrl}}/v1/examples/update-many HTTP/1.1
Accept: application/json
Content-Type: application/json

{
  "filter": {
    "name": "{{name}}"
  },
  "data": {
    "phone": "{{phone}}"
  }
}