name: build-and-deploy

on:
  push:
    branches:
      - main
      - staging
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - main
      - staging

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.6.0
        with:
          mongodb-version: 6.0.12
          mongodb-replica-set: replica-set
          mongodb-port: 27001

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Install dependencies
        run: bun test
